/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proov1;

public class App {
    public static void main(String[] args) {

    }
        
    public static Integer multiply(Integer a, Integer b){
        return a * b;
    }

    public static double sum(double a, double b){
        return a + b;
    }
    public static double subtract(double a, double b){
        return a-b;
    }
}
