/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proov1;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
   	@Test public void SRAVNENIE(){
		// assertEquals(5, 2 + 2);
		assertEquals(4, App.multiply(2, 2), 0.01);
		assertEquals(-1, App.subtract(3.0, 4.0), 0.01);
        assertEquals(7.0, App.sum(3.0, 4.0), 0.01);
	}

}

